language: node_js
node_js:
  - '0.10'
before_install:
  - 'npm install -g bower grunt-cli'
install:
  - 'npm cache clean'
  - 'npm install'
  - 'bower install --allow-root'
before_script:
  - 'grunt --force'